name: shopify

description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

#==================================  Dependencies  Section  ==============================
dependencies:
  flutter:
    sdk: flutter

# dependency to can make icon for my app
  flutter_launcher_icons: ^0.13.1
  # dependency to can use svg images
  flutter_svg: ^2.0.10+1
  # dependency for my services
  get_it: ^8.0.2
  # dependency for either return type
  dartz: ^0.10.1
  # dependency for state managment
  flutter_bloc: ^8.1.6
  # dependency for svg picture image when used with non svg images
  flutter_svg_provider: ^1.0.7
  # dependency for handle bottom nav bar
  persistent_bottom_nav_bar: ^6.2.1

  # firebase dependencies
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  email_validator: ^3.0.0
  google_sign_in: ^6.2.1
  flutter_facebook_auth: ^7.1.1
  sign_in_with_apple: ^6.1.3
  crypto: ^3.0.6
  shared_preferences: ^2.3.2
  cupertino_icons: ^1.0.8

#==================================  Dev  Dependencies  Section  ==============================
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 24 # android min sdk min:16, default 21
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/logo.png"

  # The "flutter_lints" package below contains a set of recommended lints to
  flutter_lints: ^4.0.0


#==================================  Flutter  Section Add Images and Fonts ==============================
flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/vectors/
    - assets/images/

  fonts:
    - family: CircularStd
      fonts:
        - asset: assets/fonts/CircularStd-Black.ttf
          weight: 800
        - asset: assets/fonts/CircularStd-Bold.ttf
          weight: 700
        - asset: assets/fonts/CircularStd-Medium.ttf
          weight: 500
        - asset: assets/fonts/CircularStd-Regular.ttf
          weight: 400